// react-image-slider/src/components/ImageSlider.js
import React, { useState } from 'react'

const ImageSlider = ({ slides }) => {
    const [currentIndex, setCurrentIndex] = useState(0);
    const sliderStyles = {  
        position: "relative",
        height: "100%",
    };
    const slideStyles = { 
        backgroundImage: `url(${slides[currentIndex].url})`, 
        width: '100%', 
        height: '100%', 
        borderRadius: '10px',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
    };
    const leftArrowSytles = {
        position: "absolute",
        top: "50%",
        transform: "translate(0, -50%)",
        left: "32px",
        fontSize: "45px",
        color: "#fff",
        zIndex: 1,
        cursor: "pointer",
    }
    const rightArrowSytles = {
        position: "absolute",
        top: "50%",
        transform: "translate(0, -50%)",
        right: "32px",
        fontSize: "45px",
        color: "#fff",
        zIndex: 1,
        cursor: "pointer",
    }

    const indicatorContainerStyles = {
        display: 'flex',
        justifyContent: 'center'
    }
    const indicatorStyles = {
        margin: '0 3px',
        fontSize: '20px',
        cursor: "pointer",
    }
    
    function onNext(){
        const isLastSlide = currentIndex === slides.length -1;
        const index = isLastSlide ? 0 : currentIndex + 1;
        setCurrentIndex(index)
    }
    function onPrevious(){
        const isFirstSlide = currentIndex === 0;
        const index = isFirstSlide ? slides.length - 1 : currentIndex - 1;
        setCurrentIndex(index)
    }
    function onIndicator(index){
        setCurrentIndex(index)
    }
    return (
        <div style={sliderStyles}>
            <div style={leftArrowSytles} onClick={onPrevious}>❰</div>
            <div style={rightArrowSytles} onClick={onNext}>❱</div>
            <div style={slideStyles}></div>
            <div style={indicatorContainerStyles}>
                {slides.map((slide, slideIndex) => 
                    <div style={indicatorStyles} key={slideIndex} onClick={() => onIndicator(slideIndex)}>●</div>      
                )}
            </div>
        </div>
    )
}

export default ImageSlider;

// vue-image-slider/src/components/ImageSlider.vue
<template>
  <div class="slider">
    <div class="arrow-left" @click="onPrevious()">❰</div>
    <div class="arrow-right" @click="onNext()">❱</div>
    <div
      class="slide"
      style="{background-image: `url(' + slides[currentIndex].url + ')`}"
    ></div>
    <!-- <div class="indicators">
      <div
        class="indicator"
        :class="{ active: currentIndex === index }"
        v-for="{item,index} in slides"
        :key="index"
        @click="onIndex(index)"
      >
        ●
      </div>
    </div> -->
  </div>
</template>

<script>
export default {
  name: "ImageSlider",
  props: ["slides"],
  data() {
    return {
      currentIndex: 0,
    };
  },
  methods: {
    onPrevious() {
      const isFirstIndex = this.currentIndex === 0;
      this.currentIndex = isFirstIndex ? this.slides.length - 1 : this.currentIndex - 1;
    },
    onNext() {
      const isLastIndex = this.currentIndex === this.slides.length - 1;
      this.currentIndex = isLastIndex ? 0 : this.currentIndex + 1;
    },
    onIndex(index) {
      this.currentIndex = index;
    },
  },
};
</script>

<style scoped>
.slider {
  width: 100%;
  height: 100%;
  position: relative;
}

.slide {
  width: 100%;
  height: 100%;
  border-radius: 10px;
  background-position: center;
  background-size: cover;
}

.arrow-left {
  position: absolute;
  top: calc(50% - 34px);
  left: 30px;
  font-size: 72px;
  color: white;
  opacity: 0.3;
  cursor: pointer;
}
.arrow-left:hover {
  opacity: 1;
}
.arrow-right {
  position: absolute;
  top: calc(50% - 34px);
  right: 30px;
  font-size: 72px;
  color: white;
  opacity: 0.3;
  cursor: pointer;
}
.arrow-right:hover {
  opacity: 1;
}

.indicators {
  display: flex;
  justify-content: center;
}
.indicator {
  font-size: 30px;
  margin: 5px;
  cursor: pointer;
}

.active {
  color: gray;
  cursor: no-drop;
}
</style>
